---
title: 
output: 
  html_document:
    toc: TRUE
    toc_float: FALSE
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Function, echo=TRUE, cache=TRUE, eval=TRUE}
#function that is going to be applied to weeks 5:21
scrap_football_data <-function(url) {
  library("httr")
  html_code <- GET(url)
  html_code <- content(html_code, "text", encoding = "ISO-8859-1")
  html_code <- gsub(x = html_code, pattern = "[[:cntrl:]]", replacement = "")
  html_code <- gsub(x = html_code, pattern = "[[:blank:]]+", replacement = " ") 
  
  #Getting Team Names
  Team_Names <- gregexpr(pattern = "TARGET=\"_BLANK\">.+?</TD>", text=html_code)
  matches    <- regmatches(x=html_code, m=Team_Names)
  Team_Names <- matches[[1]]
  Team_Names <- substr(x=Team_Names, start=17, nchar(Team_Names)-9) #removing the first html tags and the last to only have which teams won left
  Team_Names <- unique(head(Team_Names,-2)) # Removing the last two because they're from the tie breakers section 
  Team_Names <- gsub(x=Team_Names, pattern="<B>|</B>", replacement="")
  
  #Getting which teams won next
  Winning_Team <- gregexpr(pattern = "TARGET=\"_BLANK\"><B>.+?</B></A></TD>", html_code)
  matches      <- regmatches(x=html_code, m=Winning_Team)
  Winning_Team <- matches[[1]]
  Winning_Team <- substr(x=Winning_Team, start=20, nchar(Winning_Team)-13)
  Winning_Team <- unique(head(Winning_Team, -1)) #Removing the last one because its from the tie breaker section 
  
  #Getting the home team by using a sequence
  Home_Team <- Team_Names[seq(from=1, to=length(Team_Names), by=2)]
  #Getting the away team by using a sequence
  Away_Team <- Team_Names[seq(from=2, to=length(Team_Names), by=2)]
  
  #Getting percentages
  Prediction_Teams <- gregexpr(pattern="align=center><NOBR>.+?</NOBR></TD>", text=html_code)
  matches          <- regmatches(x=html_code, m=Prediction_Teams)
  Prediction_Teams <- matches[[1]]
  Prediction_Teams <- substr(x=Prediction_Teams, start=20, nchar(Prediction_Teams)-12)
  Prediction_Teams <- gsub(x=Prediction_Teams, pattern="<B>|</B>", replacement="")
  Prediction_Teams <- gsub(x=Prediction_Teams, pattern="%", replacement="")
  
  #Getting prediction for home and away using sequence again
  Prediction_Home_Team <- Prediction_Teams[seq(from=1, to=length(Prediction_Teams), by=2)]
  Prediction_Away_Team <- Prediction_Teams[seq(from=2, to=length(Prediction_Teams), by=2)]
  
  #Creating data frame with vectors
  result <- data.frame(Home_Team, Away_Team, Winning_Team, Prediction_Home_Team, Prediction_Away_Team)
  result
  return(result)
}
```

```{r ForLoop, echo=TRUE, cache=TRUE, eval=TRUE}
#creating a for loop to run the function over each week of the url, having it rbind the rows from each result into another data frame
Football_data <- NULL
for (week in 5:21){
  url <- paste0("https://probabilityfootball.com/picks.html?1487349677&username=AVERAGES&weeknum=", week, "")
  week <- scrap_football_data(url)
  Football_data <- rbind(Football_data, week)
}

library(knitr)
kable(head(Football_data), caption = "First Six Results From Football_Data")
```

```{r TTest, echo=TRUE, cache=TRUE, eval=TRUE}
probability_winner <- ifelse(Football_data$Winning_Team == Football_data$Home_Team, 
                             as.character(Football_data$Prediction_Home_Team), 
                             as.character(Football_data$Prediction_Away_Team))

Football_data$probability_winner <- probability_winner

Football_data$probability_winner <- as.integer(Football_data$probability_winner) # was character before, but we need it to be integer in order to do t test

t_test <- t.test(Football_data$probability_winner, mu=50, alternative = "greater")

library(pander)
pander(t_test)

# On average, an expert is more accurate than a coin. While this model states that experts perform better than a coin, I would still be wary about 
# suggesting using an expert-driven forecast instead of model-based forecasts until I could see how this forecast would compare to a model-based one.
# Further
```

