---
title: "Adam Bandola's Website"
description: |
site: distill::distill_website
---
### Welcome to my website, I hope you enjoy it. Below is everything that is needed to know about it!
The <b><i> Welcome </i></b> tab is where you can find out a little bit about me. This includes my education, experience and campus involvement. It also has links to my email, LinkedIn and Github url's. <br> <br>
The <b><i> Relevant Projects </i></b> tab is where you can find projects that I have completed, on my own, throughout my courses. It showcases a portion of my skills, however, my skills are not limited to those only shown on this tab. 
<br><br> 
The reason for me creating this site is rather simple. I wanted a way to showcase my abilities outside of a resume and to offer a more interactive method to get to know me. Consider this website as my virtual handshake to you, from me. 

##### With that being said, I urge you to explore the website to your liking and if you have any questions, or want to contact me via email or LinkedIn, please feel free to reach out!

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

